/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workingmemory.gui;

import javax.swing.DefaultListModel;
import workingmemory.core.entities.WMItem;

/**
 *
 * @author Luis Martin
 */
public class MemoryFrame extends javax.swing.JFrame {

    /**
     * Creates new form MemoryFrame
     */
    
    private DefaultListModel model;
    
    public MemoryFrame(String label) {
        initComponents();
        
        setTitle(label);
        labelTxt.setText(label);
        
        model = new DefaultListModel();
        itemList.setModel(model);
        
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    
    public void addItem(WMItem item){
        model.addElement(item);
    }
    
    public void remove(WMItem item){
        model.removeElement(item);
    }
    
    public void update(WMItem item){
        int index = model.indexOf(item);
        model.set(index, item);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList<>();
        labelTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        itemList.setPreferredSize(new java.awt.Dimension(42, 150));
        jScrollPane1.setViewportView(itemList);

        labelTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTxt.setText("Content of PFC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addComponent(labelTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTxt)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> itemList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTxt;
    // End of variables declaration//GEN-END:variables
}
